minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Developers are Artists"
title_separator          : "-"
name                     : &name "Amos Syuma"
description              : &description "Musings about cloud and mobile development."
url                      : &url "https://syumaK.github.io"
baseurl                  : "syumaK.github.io"
repository               : "syumaK/syumaK.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
breadcrumbs              : true
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "syumaK.github.io"
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_full_content      : true
search_provider          : lunr
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : &twitter syumaK8

# Site Author
author:
  name             : *name
  avatar           : "/assets/images/adrian-hall.jpg"
  bio              : "Cloud Engineer by day; Cloud Developer by night"
  location         : "Cape Town, SA"
  email            : "amossyuma@gmail.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://syumaK.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/syumaK8"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/syumaK"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:amossyuma@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: *url
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/syumaK8"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/syumaK"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "md"




# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
safe: true
gist:
  noscript: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: mathjax
  syntax_highlighter: rouge


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed


# Outputting
permalink: pretty
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "US/Pacific"


# Plugins (previously gems:)
plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-coffeescript
  - jekyll-readme-index
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      toc: true
      comments: true
      share: true
      related: true
